package com.app.entities;

public enum ServiceType {
	CARPENTER,ELECTRICIAN,PLUMBER,PAINTER,HOUSEKEEPING,PC_CARE,MOBILE_REPAIR,LAUNDRYMAN,VEGETABLE_VENDOR,GENERAL_STORE,PHARMACY,SALON,PATHOLOGY_LAB
}
